stages:
  data_ingestion:
    cmd: python src/bgremove/pipeline/stage_01_data_ingestion.py
    deps:
      - src/bgremove/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/

  prepare_base_model:
    cmd: python src/bgremove/pipeline/stage_02_base_model.py
    deps:
      - src/bgremove/pipeline/stage_02_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - OUT_CH
      - INT_CH
      - CLASSES
    outs:
      - artifacts/prepare_base_model/base_model.h5
    
  training:
    cmd: python src/bgremove/pipeline/stage_03_training.py
    deps: 
      - src/bgremove/pipeline/stage_03_training.py
      - src/bgremove/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/base_model/
    params:
      - HEIGHT
      - WIDTH
      - EPOCHS
      - BATCH_SIZE
      - LEARNING_RATE
      - VERBOSE 
      - MIN_LR
      - SAVE_BEST_ONLY
      - RESTORE_BEST_WEIGHTS
      - PATIENCE_EARLY_STOPPING
      - PATIENCE_REDUCE_LEARNING
    outs:
      - artifacts/training/model.h5