# Model Params
AUGMENTATION: True

IMAGE_SIZE: [256, 256, 3] 
BATCH_SIZE: 8
EPOCHS: 2
INITIAL_EPOCHS: 1

CLASSES: 1
WEIGHTS: u2net
LEARNING_RATE: 0.00001
OUT_CH: [64, 128, 256, 512, 512, 512, 512, 256, 128, 64, 64]
INT_CH: [32, 32, 64, 128, 256, 256, 256, 128, 64, 32, 16]

# call back Params
MONITOR : "val_loss"
FACTOR: 0.1
PATIENCE_REDUCE_LEARNING: 1
PATIENCE_EARLY_STOPPING: 50
RESTORE_BEST_WEIGHTS: True
SAVE_BEST_ONLY: True
MIN_LR: 0.0000001
VERBOSE: 0


HEIGHT: 256
WIDTH: 256
   