artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  # source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  source_URL: https://drive.google.com/u/0/uc?id=1LqUU7BZeiq8I3i5KxApdOJ2haXm-cEv1&export=download
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion